export { default as UpdateTeacher } from "../Teacher.module/Component/UpdateTeacher"
export { default as TeachersByID } from "../Teacher.module/Component/TeachersByID"
export { default as TeacherHome } from "../Teacher.module/Component/TeacherHome"
export { default as TeacherALL } from "../Teacher.module/Component/TeacherALL"
export { default as CreateTeacher } from "../Teacher.module/Component/CreateTeacher"
export { default as Teacher } from "../Teacher.module/Component/Teacher"